# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infaas_request_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1binfaas_request_status.proto\x12\x0finfaas.internal\"\\\n\x13InfaasRequestStatus\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.infaas.internal.InfaasRequestStatusEnum\x12\x0b\n\x03msg\x18\x02 \x01(\t*D\n\x17InfaasRequestStatusEnum\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bUNAVAILABLE\x10\x02\x62\x06proto3')

_INFAASREQUESTSTATUSENUM = DESCRIPTOR.enum_types_by_name['InfaasRequestStatusEnum']
InfaasRequestStatusEnum = enum_type_wrapper.EnumTypeWrapper(_INFAASREQUESTSTATUSENUM)
INVALID = 0
SUCCESS = 1
UNAVAILABLE = 2


_INFAASREQUESTSTATUS = DESCRIPTOR.message_types_by_name['InfaasRequestStatus']
InfaasRequestStatus = _reflection.GeneratedProtocolMessageType('InfaasRequestStatus', (_message.Message,), {
  'DESCRIPTOR' : _INFAASREQUESTSTATUS,
  '__module__' : 'infaas_request_status_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.InfaasRequestStatus)
  })
_sym_db.RegisterMessage(InfaasRequestStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFAASREQUESTSTATUSENUM._serialized_start=142
  _INFAASREQUESTSTATUSENUM._serialized_end=210
  _INFAASREQUESTSTATUS._serialized_start=48
  _INFAASREQUESTSTATUS._serialized_end=140
# @@protoc_insertion_point(module_scope)
