# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import infaas_request_status_pb2 as infaas__request__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x0finfaas.internal\x1a\x1binfaas_request_status.proto\"G\n\x08QuerySLO\x12\x15\n\rLatencyInUSec\x18\x01 \x01(\x03\x12\x13\n\x0bMinAccuracy\x18\x02 \x01(\x02\x12\x0f\n\x07MaxCost\x18\x03 \x01(\x02\"q\n\x12QueryOnlineRequest\x12\x11\n\traw_input\x18\x01 \x03(\x0c\x12\r\n\x05model\x18\x02 \x03(\t\x12&\n\x03slo\x18\x03 \x01(\x0b\x32\x19.infaas.internal.QuerySLO\x12\x11\n\tsubmitter\x18\x04 \x01(\t\"_\n\x13QueryOnlineResponse\x12\x12\n\nraw_output\x18\x01 \x03(\x0c\x12\x34\n\x06status\x18\x02 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"\x86\x01\n\x13QueryOfflineRequest\x12\x11\n\tinput_url\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x03(\t\x12\x12\n\noutput_url\x18\x03 \x01(\t\x12&\n\x03slo\x18\x04 \x01(\x0b\x32\x19.infaas.internal.QuerySLO\x12\x11\n\tsubmitter\x18\x05 \x01(\t\"L\n\x14QueryOfflineResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"H\n\x10HeartbeatRequest\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus\"I\n\x11HeartbeatResponse\x12\x34\n\x06status\x18\x01 \x01(\x0b\x32$.infaas.internal.InfaasRequestStatus2\x98\x02\n\x05Query\x12Z\n\x0bQueryOnline\x12#.infaas.internal.QueryOnlineRequest\x1a$.infaas.internal.QueryOnlineResponse\"\x00\x12]\n\x0cQueryOffline\x12$.infaas.internal.QueryOfflineRequest\x1a%.infaas.internal.QueryOfflineResponse\"\x00\x12T\n\tHeartbeat\x12!.infaas.internal.HeartbeatRequest\x1a\".infaas.internal.HeartbeatResponse\"\x00\x62\x06proto3')



_QUERYSLO = DESCRIPTOR.message_types_by_name['QuerySLO']
_QUERYONLINEREQUEST = DESCRIPTOR.message_types_by_name['QueryOnlineRequest']
_QUERYONLINERESPONSE = DESCRIPTOR.message_types_by_name['QueryOnlineResponse']
_QUERYOFFLINEREQUEST = DESCRIPTOR.message_types_by_name['QueryOfflineRequest']
_QUERYOFFLINERESPONSE = DESCRIPTOR.message_types_by_name['QueryOfflineResponse']
_HEARTBEATREQUEST = DESCRIPTOR.message_types_by_name['HeartbeatRequest']
_HEARTBEATRESPONSE = DESCRIPTOR.message_types_by_name['HeartbeatResponse']
QuerySLO = _reflection.GeneratedProtocolMessageType('QuerySLO', (_message.Message,), {
  'DESCRIPTOR' : _QUERYSLO,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QuerySLO)
  })
_sym_db.RegisterMessage(QuerySLO)

QueryOnlineRequest = _reflection.GeneratedProtocolMessageType('QueryOnlineRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYONLINEREQUEST,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOnlineRequest)
  })
_sym_db.RegisterMessage(QueryOnlineRequest)

QueryOnlineResponse = _reflection.GeneratedProtocolMessageType('QueryOnlineResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYONLINERESPONSE,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOnlineResponse)
  })
_sym_db.RegisterMessage(QueryOnlineResponse)

QueryOfflineRequest = _reflection.GeneratedProtocolMessageType('QueryOfflineRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYOFFLINEREQUEST,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOfflineRequest)
  })
_sym_db.RegisterMessage(QueryOfflineRequest)

QueryOfflineResponse = _reflection.GeneratedProtocolMessageType('QueryOfflineResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYOFFLINERESPONSE,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.QueryOfflineResponse)
  })
_sym_db.RegisterMessage(QueryOfflineResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:infaas.internal.HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)

_QUERY = DESCRIPTOR.services_by_name['Query']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYSLO._serialized_start=61
  _QUERYSLO._serialized_end=132
  _QUERYONLINEREQUEST._serialized_start=134
  _QUERYONLINEREQUEST._serialized_end=247
  _QUERYONLINERESPONSE._serialized_start=249
  _QUERYONLINERESPONSE._serialized_end=344
  _QUERYOFFLINEREQUEST._serialized_start=347
  _QUERYOFFLINEREQUEST._serialized_end=481
  _QUERYOFFLINERESPONSE._serialized_start=483
  _QUERYOFFLINERESPONSE._serialized_end=559
  _HEARTBEATREQUEST._serialized_start=561
  _HEARTBEATREQUEST._serialized_end=633
  _HEARTBEATRESPONSE._serialized_start=635
  _HEARTBEATRESPONSE._serialized_end=708
  _QUERY._serialized_start=711
  _QUERY._serialized_end=991
# @@protoc_insertion_point(module_scope)
